---
version: '3'
services:
  # for debug
  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6380:6379"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beehive
      MYSQL_USER: beehive
      MYSQL_PASSWORD: beehive
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
